import datetime
import uuid
import logging
from typing import Optional, Dict, Any, List
from sqlalchemy.orm import Session
from backend.models.all_models import AuditLog
from backend.events.taxonomy import (
    ALL_CANONICAL_EVENTS, RecoveryEventType, PaymentEventType
)

logger = logging.getLogger(__name__)

# Legacy mapping for backwards compatibility
LEGACY_EVENT_MAP = {
    "EVENT_DETECTED": PaymentEventType.PAYMENT_FAILED.value,
    "RISK_SCORED": RecoveryEventType.RISK_SCORED.value,
    "AI_DIAGNOSED": RecoveryEventType.AI_DIAGNOSED.value,
    "POLICY_VALIDATED": RecoveryEventType.POLICY_PASSED.value,
    "ACTION_RECOMMENDED": RecoveryEventType.ACTION_RECOMMENDED.value,
    "ACTION_EXECUTED": RecoveryEventType.ACTION_EXECUTED.value,
    "PAYMENT_RECOVERED": RecoveryEventType.VERIFIED.value,
    "ESCALATED": RecoveryEventType.ESCALATED.value,
    "STOPPED": RecoveryEventType.STOPPED.value,
}

class AuditService:
    @classmethod
    def log_event(
        cls,
        db: Session,
        case_id: Optional[str],
        actor: str,
        action: str,
        input_data: Optional[Dict[str, Any]] = None,
        decision: Optional[Dict[str, Any]] = None,
        policy_result: Optional[str] = None,
        execution_result: Optional[str] = None,
        notes: Optional[str] = None,
        actor_type: str = "SYSTEM",
        source: str = "RAZORPAY_TEST",
        source_description: Optional[str] = None,
        before_state: Optional[Dict[str, Any]] = None,
        after_state: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> AuditLog:
        """
        Creates an immutable, traceable canonical domain AuditLog entry with provenance tracking.
        """
        audit_id = f"aud_{uuid.uuid4().hex[:12]}"
        canonical_event = LEGACY_EVENT_MAP.get(action, action)
        
        desc = source_description or (
            "Synthetic event generated by RevivePay" if source == "SIMULATION" else "Event received from Razorpay Test environment"
        )

        log = AuditLog(
            audit_id=audit_id,
            case_id=case_id,
            source=source,
            source_description=desc,
            event_type=canonical_event,
            actor_type=actor_type,
            actor_id=actor,
            before_state=before_state,
            after_state=after_state,
            metadata_json=metadata or input_data,
            timestamp=datetime.datetime.utcnow(),
            # Compatibility properties
            action=canonical_event,
            actor=actor,
            input_data=input_data,
            decision=decision,
            policy_result=policy_result,
            execution_result=execution_result,
            notes=notes
        )
        db.add(log)
        db.commit()
        db.refresh(log)
        return log

    @classmethod
    def get_logs_for_case(cls, db: Session, case_id: str) -> List[AuditLog]:
        return db.query(AuditLog).filter(
            (AuditLog.case_id == case_id)
        ).order_by(AuditLog.timestamp.asc()).all()
