import datetime
import uuid
import logging
import hashlib
from typing import Optional, Dict, Any, List, Tuple
from sqlalchemy.orm import Session
from backend.models.all_models import AuditLog
from backend.events.taxonomy import (
    ALL_CANONICAL_EVENTS, RecoveryEventType, PaymentEventType
)

logger = logging.getLogger(__name__)

GENESIS_HASH = "0000000000000000000000000000000000000000000000000000000000000000"

# Legacy mapping for backwards compatibility
LEGACY_EVENT_MAP = {
    "EVENT_DETECTED": PaymentEventType.PAYMENT_FAILED.value,
    "RISK_SCORED": RecoveryEventType.RISK_SCORED.value,
    "AI_DIAGNOSED": RecoveryEventType.AI_DIAGNOSED.value,
    "POLICY_VALIDATED": RecoveryEventType.POLICY_PASSED.value,
    "ACTION_RECOMMENDED": RecoveryEventType.ACTION_RECOMMENDED.value,
    "ACTION_EXECUTED": RecoveryEventType.ACTION_EXECUTED.value,
    "PAYMENT_RECOVERED": RecoveryEventType.VERIFIED.value,
    "ESCALATED": RecoveryEventType.ESCALATED.value,
    "STOPPED": RecoveryEventType.STOPPED.value,
}

class AuditService:
    @classmethod
    def _compute_hash(
        cls,
        prev_hash: str,
        audit_id: str,
        timestamp_str: str,
        actor: str,
        action: str,
        case_id: Optional[str],
        notes: Optional[str]
    ) -> str:
        payload = f"{prev_hash}|{audit_id}|{timestamp_str}|{actor}|{action}|{case_id or ''}|{notes or ''}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    @classmethod
    def log_event(
        cls,
        db: Session,
        case_id: Optional[str],
        actor: str,
        action: str,
        input_data: Optional[Dict[str, Any]] = None,
        decision: Optional[Dict[str, Any]] = None,
        policy_result: Optional[str] = None,
        execution_result: Optional[str] = None,
        notes: Optional[str] = None,
        actor_type: str = "SYSTEM",
        source: str = "RAZORPAY_TEST",
        source_description: Optional[str] = None,
        before_state: Optional[Dict[str, Any]] = None,
        after_state: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> AuditLog:
        """
        Creates an immutable, traceable, cryptographically hash-chained AuditLog entry.
        """
        audit_id = f"aud_{uuid.uuid4().hex[:12]}"
        canonical_event = LEGACY_EVENT_MAP.get(action, action)
        now = datetime.datetime.utcnow()
        now_str = now.isoformat()
        
        desc = source_description or (
            "Synthetic event generated by RevivePay" if source == "SIMULATION" else "Event received from Razorpay Test environment"
        )

        # Get previous hash from the latest audit log
        latest_log = db.query(AuditLog).order_by(AuditLog.timestamp.desc()).first()
        prev_hash = latest_log.entry_hash if (latest_log and latest_log.entry_hash) else GENESIS_HASH

        # Compute SHA-256 block hash
        current_hash = cls._compute_hash(
            prev_hash=prev_hash,
            audit_id=audit_id,
            timestamp_str=now_str,
            actor=actor,
            action=canonical_event,
            case_id=case_id,
            notes=notes
        )

        log = AuditLog(
            audit_id=audit_id,
            case_id=case_id,
            source=source,
            source_description=desc,
            event_type=canonical_event,
            actor_type=actor_type,
            actor_id=actor,
            before_state=before_state,
            after_state=after_state,
            metadata_json=metadata or input_data,
            timestamp=now,
            entry_hash=current_hash,
            previous_hash=prev_hash,
            # Compatibility properties
            action=canonical_event,
            actor=actor,
            input_data=input_data,
            decision=decision,
            policy_result=policy_result,
            execution_result=execution_result,
            notes=notes
        )
        db.add(log)
        db.commit()
        db.refresh(log)
        return log

    @classmethod
    def get_logs_for_case(cls, db: Session, case_id: str) -> List[AuditLog]:
        return db.query(AuditLog).filter(
            (AuditLog.case_id == case_id)
        ).order_by(AuditLog.timestamp.asc()).all()

    @classmethod
    def verify_chain(cls, db: Session) -> Dict[str, Any]:
        """
        Walks the entire audit log from genesis to head and verifies SHA-256 cryptographic linkage.
        """
        logs = db.query(AuditLog).order_by(AuditLog.timestamp.asc(), AuditLog.audit_id.asc()).all()
        if not logs:
            return {
                "valid": True,
                "total_blocks": 0,
                "genesis_hash": GENESIS_HASH,
                "head_hash": GENESIS_HASH,
                "status": "EMPTY_CHAIN"
            }

        expected_prev_hash = GENESIS_HASH
        for idx, log in enumerate(logs):
            if log.previous_hash != expected_prev_hash:
                return {
                    "valid": False,
                    "error": f"Broken link at block {idx} (ID: {log.audit_id}). Expected previous hash {expected_prev_hash}, got {log.previous_hash}",
                    "broken_block_id": log.audit_id,
                    "total_blocks": len(logs),
                    "status": "CORRUPTED"
                }

            expected_hash = cls._compute_hash(
                prev_hash=log.previous_hash or GENESIS_HASH,
                audit_id=log.audit_id,
                timestamp_str=log.timestamp.isoformat() if log.timestamp else "",
                actor=log.actor or "",
                action=log.action or log.event_type or "",
                case_id=log.case_id,
                notes=log.notes
            )

            if log.entry_hash != expected_hash:
                return {
                    "valid": False,
                    "error": f"Hash mismatch at block {idx} (ID: {log.audit_id}). Expected {expected_hash}, recorded {log.entry_hash}",
                    "broken_block_id": log.audit_id,
                    "total_blocks": len(logs),
                    "status": "TAMPERED"
                }

            expected_prev_hash = log.entry_hash

        return {
            "valid": True,
            "total_blocks": len(logs),
            "genesis_hash": logs[0].entry_hash if logs else GENESIS_HASH,
            "head_hash": logs[-1].entry_hash if logs else GENESIS_HASH,
            "status": "CRYPTOGRAPHICALLY_VERIFIED"
        }
