import datetime
import logging
import uuid
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from backend.models.all_models import (
    RecoveryCase, Payment, Customer, Merchant, PolicyConfig,
    PaymentEvent, AgentDecision, RecoveryAction, PolicyEvaluation,
    Approval, Notification, AuditLog
)
from backend.events.taxonomy import (
    PaymentEventType, RecoveryEventType
)
from backend.services.risk_engine import RevenueRiskEngine
from backend.services.ai_agent import ai_service
from backend.services.policy_gateway import PolicyGateway
from backend.services.razorpay_service import RazorpayService
from backend.services.audit_service import AuditService
from backend.services.outcome_verification_service import OutcomeVerificationService
from backend.services.broadcaster import notify_live_event
from backend.services.state_machine import RecoveryStateMachine, RecoveryState

logger = logging.getLogger(__name__)

class RecoveryEngine:
    @classmethod
    def process_payment_failure(
        cls,
        db: Session,
        payment: Payment,
        customer: Customer,
        merchant: Merchant
    ) -> RecoveryCase:
        """
        End-to-End Domain Orchestrator with Canonical Event Taxonomy:
        1. Ingest PaymentEvent (payment.failed)
        2. Create RecoveryCase (recovery.case.created)
        3. Risk Engine (recovery.risk.scored)
        4. AI Diagnosis (recovery.ai.diagnosed & recovery.action.recommended)
        5. Policy Gateway (recovery.policy.passed or recovery.policy.blocked)
        6. Approval Handling (recovery.approval.requested)
        """
        # Ensure merchant policy config exists
        policy = db.query(PolicyConfig).filter(PolicyConfig.merchant_id == merchant.merchant_id).first()
        if not policy:
            policy = PolicyConfig(merchant_id=merchant.merchant_id)
            db.add(policy)
            db.commit()
            db.refresh(policy)

        # 1. Ingest PaymentEvent (payment.failed) if not already created at webhook ingress
        src = getattr(payment, "source", "RAZORPAY_TEST") or "RAZORPAY_TEST"
        src_desc = getattr(payment, "source_description", None) or (
            "Synthetic event generated by RevivePay" if src == "SIMULATION" else "Event received from Razorpay Test environment"
        )

        existing_pe = db.query(PaymentEvent).filter(
            PaymentEvent.payment_id == payment.payment_id,
            PaymentEvent.event_type.in_([PaymentEventType.PAYMENT_FAILED.value, "payment.failed"])
        ).first()

        if not existing_pe:
            evt_id = f"evt_{uuid.uuid4().hex[:12]}"
            payment_event = PaymentEvent(
                event_id=evt_id,
                provider=payment.provider or "razorpay",
                provider_event_id=f"pvt_evt_{uuid.uuid4().hex[:8]}",
                event_type=PaymentEventType.PAYMENT_FAILED.value,
                payment_id=payment.payment_id,
                source=src,
                source_description=src_desc,
                payload_hash=f"hash_{uuid.uuid4().hex[:16]}",
                payload={"amount": payment.amount, "failure_code": payment.failure_code, "reason": payment.failure_reason},
                received_at=datetime.datetime.utcnow(),
                processed_at=datetime.datetime.utcnow(),
                processing_status="PROCESSED"
            )
            db.add(payment_event)
            db.commit()

        # Check if recovery case already exists for this payment
        case = db.query(RecoveryCase).filter(RecoveryCase.payment_id == payment.payment_id).first()
        if not case:
            case_number = f"RV-{datetime.datetime.utcnow().strftime('%m%d')}{uuid.uuid4().hex[:4].upper()}"
            
            # Compute RBI Turn Around Time (TAT) deadline based on payment method
            now = datetime.datetime.utcnow()
            pm = getattr(payment, "payment_method", "card") or "card"
            if str(pm).lower() == "upi":
                tat_deadline = now + datetime.timedelta(days=1)
            else:
                # 5 working days (7 calendar days)
                tat_deadline = now + datetime.timedelta(days=7)

            case = RecoveryCase(
                case_id=case_number,
                payment_id=payment.payment_id,
                customer_id=customer.customer_id,
                source=src,
                source_description=src_desc,
                case_type="PAYMENT_FAILURE",
                amount_at_risk=payment.amount,
                risk_score=50.0,
                risk_level="MEDIUM",
                recovery_status="NEW",
                approval_required=False,
                outcome_verified=False,
                recovered_amount=0.0,
                tat_deadline=tat_deadline,
                tat_status="ON_TRACK",
                accrued_compensation_inr=0.0
            )
            db.add(case)
            db.commit()
            db.refresh(case)

            AuditService.log_event(
                db=db,
                case_id=case.case_id,
                actor="Razorpay Ingestion Engine" if src == "RAZORPAY_TEST" else "Simulation Ingestion Node",
                action=RecoveryEventType.CASE_CREATED.value,
                actor_type="GATEWAY" if src == "RAZORPAY_TEST" else "SYSTEM",
                source=src,
                source_description=src_desc,
                decision={"risk_score": case.risk_score, "risk_level": case.risk_level},
                notes=f"Recovery case created from {'Razorpay Test Mode event' if src == 'RAZORPAY_TEST' else 'Synthetic simulation event'}."
            )

        # IDEMPOTENCY / INVARIANT GUARD 0: If case is already terminal, return immediately (zero double-counting)
        if case.recovery_status in ["RECOVERED", "STOPPED", "REJECTED"]:
            logger.info(f"Payment {payment.payment_id} has existing terminal recovery case {case.case_id} ({case.recovery_status}). Skipping duplicate pipeline execution.")
            return case

        # IDEMPOTENCY GUARD 1: If case is already in progress beyond NEW, return existing case without duplicate pipeline re-run
        if case.recovery_status != "NEW":
            logger.info(f"Payment {payment.payment_id} already has active recovery case {case.case_id} ({case.recovery_status}). Skipping duplicate pipeline invocation.")
            return case

        # INVARIANT GUARD 2: If payment already succeeded, mark case recovered
        if payment.status == "SUCCESS":
            case.recovered_amount = payment.amount
            case.outcome_verified = True
            case.resolved_at = case.resolved_at or datetime.datetime.utcnow()
            case.approval_required = False
            case.approval_status = "AUTO_APPROVED"
            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="RECOVERED",
                actor="RevivePay Invariant Supervisor",
                notes="Payment was already in SUCCESS state upon ingestion."
            )
            return case

        # State Machine Progression 1: NEW -> ANALYZING
        RecoveryStateMachine.transition(
            db=db,
            case=case,
            to_state="ANALYZING",
            actor="RevivePay Telemetry Node",
            notes="Ingesting failure telemetry and executing AI root-cause diagnostics."
        )

        # 2. Deterministic Risk Engine (recovery.risk.scored)
        risk_score, risk_level, risk_factors = RevenueRiskEngine.calculate_risk(
            amount=payment.amount,
            failure_category=payment.failure_category,
            total_payments=customer.total_successful_payments + customer.total_failed_payments,
            successful_payments=customer.total_successful_payments,
            failed_payments=customer.total_failed_payments,
            retry_count=payment.retry_count,
            customer_tier=customer.account_tier
        )
        case.risk_score = risk_score
        case.risk_level = risk_level
        case.risk_factors = risk_factors

        # Canonical Event: recovery.risk.scored
        AuditService.log_event(
            db=db,
            case_id=case.case_id,
            actor="RevivePay Risk Engine",
            action=RecoveryEventType.RISK_SCORED.value,
            actor_type="SYSTEM",
            input_data={"amount": payment.amount, "failure_category": payment.failure_category},
            decision={"risk_score": risk_score, "risk_level": risk_level, "factors": risk_factors},
            notes=f"Calculated 4-factor risk score: {risk_score}/100 ({risk_level})"
        )

        # 3. AI Root-Cause Analysis Agent & Persist AgentDecision (recovery.ai.diagnosed)
        ai_context = {
            "case_id": case.case_id,
            "payment_id": payment.payment_id,
            "customer_name": customer.name if customer else "Enterprise Customer",
            "amount": payment.amount,
            "currency": payment.currency,
            "payment_method": getattr(payment, "payment_method", "card") or "card",
            "failure_category": payment.failure_category,
            "failure_code": payment.failure_code,
            "failure_reason": payment.failure_reason,
            "successful_payments": customer.total_successful_payments if customer else 0,
            "failed_payments": customer.total_failed_payments if customer else 0,
            "retry_count": payment.retry_count,
            "risk_score": risk_score,
            "customer_tier": customer.account_tier if customer else "STANDARD"
        }
        ai_analysis = ai_service.analyze_root_cause(ai_context)
        case.root_cause = ai_analysis.root_cause
        case.ai_confidence = ai_analysis.confidence
        case.evidence = ai_analysis.evidence
        case.recommended_action = ai_analysis.recommended_action
        case.reasoning_summary = ai_analysis.reasoning_summary

        # Domain Entity: AgentDecision (persists transparent model input/output audit pair)
        decision_entity = AgentDecision(
            decision_id=f"dec_{uuid.uuid4().hex[:12]}",
            case_id=case.case_id,
            model_provider=ai_analysis.model_provider or "deterministic_rules_engine",
            model_name=ai_analysis.model_name or "rules-engine-v2.1",
            prompt_version="v2.1",
            input_version="v1.0",
            root_cause=ai_analysis.root_cause,
            confidence=ai_analysis.confidence,
            evidence=ai_analysis.evidence,
            recommended_action=ai_analysis.recommended_action,
            reasoning_narrative=ai_analysis.reasoning_summary,
            prompt_raw=ai_analysis.raw_prompt,
            response_raw=ai_analysis.raw_response,
            decision_timestamp=datetime.datetime.utcnow()
        )
        db.add(decision_entity)

        # Canonical Event: recovery.ai.diagnosed (with full model provenance in audit trail)
        AuditService.log_event(
            db=db,
            case_id=case.case_id,
            actor="RevivePay AI Agent",
            action=RecoveryEventType.AI_DIAGNOSED.value,
            actor_type="AI_AGENT",
            input_data=ai_context,
            decision={
                "root_cause": ai_analysis.root_cause,
                "confidence": ai_analysis.confidence,
                "recommended_action": ai_analysis.recommended_action,
                "reasoning": ai_analysis.reasoning_summary,
                "model_provider": ai_analysis.model_provider,
                "model_name": ai_analysis.model_name
            },
            notes=f"AI Root-Cause Diagnosis via [{ai_analysis.model_provider or 'deterministic_rules_engine'}]: {ai_analysis.root_cause} ({int(ai_analysis.confidence*100)}% confidence)"
        )

        # State Machine Progression 2: ANALYZING -> ACTION_RECOMMENDED
        RecoveryStateMachine.transition(
            db=db,
            case=case,
            to_state="ACTION_RECOMMENDED",
            actor="RevivePay Root-Cause AI Agent",
            notes=f"AI diagnostic completed with {int(ai_analysis.confidence*100)}% confidence. Recommended: {ai_analysis.recommended_action}."
        )

        # 4. Deterministic Policy Gateway (recovery.policy.passed or recovery.policy.blocked)
        policy_status, checklist, overall_reason = PolicyGateway.evaluate(
            case=case,
            payment=payment,
            customer=customer,
            policy=policy,
            proposed_action=ai_analysis.recommended_action,
            ai_confidence=ai_analysis.confidence
        )
        case.policy_status = policy_status
        case.policy_checklist = checklist

        # Domain Entity: PolicyEvaluation
        policy_eval = PolicyEvaluation(
            policy_evaluation_id=f"peval_{uuid.uuid4().hex[:12]}",
            case_id=case.case_id,
            action=ai_analysis.recommended_action,
            rules_evaluated=checklist,
            decision=policy_status,
            reason=overall_reason,
            evaluated_at=datetime.datetime.utcnow(),
            policy_version="v1.0"
        )
        db.add(policy_eval)

        # Canonical Event: recovery.policy.passed or recovery.policy.blocked
        policy_event = RecoveryEventType.POLICY_PASSED.value if policy_status == "PASSED" else RecoveryEventType.POLICY_BLOCKED.value
        AuditService.log_event(
            db=db,
            case_id=case.case_id,
            actor="RevivePay Policy Gateway",
            action=policy_event,
            actor_type="SYSTEM",
            decision={"checklist": checklist, "overall_reason": overall_reason},
            policy_result=policy_status,
            notes=f"Policy Gateway evaluation: {policy_status}"
        )

        # 5. State Machine Progression 3: Invariant Status & Approval Entity Creation
        if policy_status == "BLOCKED":
            case.approval_required = False
            case.approval_status = "REJECTED"
            case.execution_status = "BLOCKED"
            case.rejection_reason = overall_reason
            case.outcome_verified = False
            case.recovered_amount = 0.0
            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="ESCALATED",
                actor="RevivePay Policy Gateway",
                notes=f"Action blocked by safety policy: {overall_reason}"
            )
        elif policy_status == "REVIEW_REQUIRED":
            case.approval_required = True
            case.approval_status = "PENDING"
            case.execution_status = "IDLE"
            case.outcome_verified = False
            case.recovered_amount = 0.0

            # Domain Entity: Approval
            approval_entity = Approval(
                approval_id=f"appr_{uuid.uuid4().hex[:12]}",
                case_id=case.case_id,
                requested_action=ai_analysis.recommended_action,
                risk_level=risk_level,
                requested_at=datetime.datetime.utcnow(),
                requested_by="Policy Gateway",
                decision="PENDING",
                decision_reason=overall_reason
            )
            db.add(approval_entity)

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="AWAITING_APPROVAL",
                actor="RevivePay Policy Gateway",
                notes="Policy evaluation requires operator sign-off before action execution."
            )
        else:  # PASSED
            if risk_level == "LOW":
                case.approval_required = False
                case.approval_status = "AUTO_APPROVED"
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="AUTO_APPROVED",
                    actor="RevivePay Policy Gateway",
                    notes="Autonomous policy gate passed without human approval required."
                )
                cls.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
            else:
                case.approval_required = True
                case.approval_status = "PENDING"
                case.execution_status = "IDLE"
                case.outcome_verified = False
                case.recovered_amount = 0.0

                approval_entity = Approval(
                    approval_id=f"appr_{uuid.uuid4().hex[:12]}",
                    case_id=case.case_id,
                    requested_action=ai_analysis.recommended_action,
                    risk_level=risk_level,
                    requested_at=datetime.datetime.utcnow(),
                    requested_by="Policy Gateway",
                    decision="PENDING",
                    decision_reason="Standard high-risk review required"
                )
                db.add(approval_entity)

                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="AWAITING_APPROVAL",
                    actor="RevivePay Policy Gateway",
                    notes="Standard high-risk review required prior to execution. Routed to Human-in-the-Loop review queue."
                )

        case.updated_at = datetime.datetime.utcnow()
        db.commit()
        db.refresh(case)

        # Broadcast live telemetry event
        notify_live_event("case_created", {
            "case_id": case.case_id,
            "amount": case.amount_at_risk,
            "customer_name": customer.name,
            "failure_type": case.failure_type,
            "risk_score": case.risk_score,
            "risk_level": case.risk_level,
            "recommended_action": case.recommended_action,
            "recovery_status": case.recovery_status,
            "source": case.source
        })

        return case

    @classmethod
    def execute_recovery_action(
        cls,
        db: Session,
        case: RecoveryCase,
        actor: str = "Operator"
    ) -> Dict[str, Any]:
        """
        Executes recovery action and logs canonical taxonomy events:
        - recovery.action.executed
        - recovery.verified (on payment captured/recovered)
        - recovery.action.failed
        - recovery.escalated
        """
        payment = case.payment
        customer = case.customer
        action = case.recommended_action
        action_id = f"act_{uuid.uuid4().hex[:12]}"
        now = datetime.datetime.utcnow()

        # Invariant 1: If case is already RECOVERED or payment already succeeded, lock
        if case.recovery_status == "RECOVERED" or (payment and payment.status == "SUCCESS"):
            case.execution_status = "COMPLETED"
            case.recovered_amount = payment.amount if payment else case.recovered_amount
            case.outcome_verified = True
            case.resolved_at = case.resolved_at or now
            if case.recovery_status != "RECOVERED":
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="RECOVERED",
                    actor="Settlement Verifier",
                    notes="Payment was already settled. Invariant enforced."
                )
            return {
                "success": True,
                "status": "RECOVERED",
                "action_id": action_id,
                "recovered_amount": case.recovered_amount,
                "message": "Payment was already settled. Invariant enforced."
            }

        # Invariant 2: Max retries guard
        max_allowed = payment.max_retry_count or 2 if payment else 2
        if action == "retry_payment" and payment and payment.retry_count >= max_allowed:
            case.execution_status = "BLOCKED"
            case.outcome_verified = False
            case.recovered_amount = 0.0
            case.resolved_at = now
            
            # Domain Entity: RecoveryAction
            rec_action = RecoveryAction(
                action_id=action_id,
                case_id=case.case_id,
                action_type=action,
                requested_by=actor,
                policy_decision=case.policy_status,
                execution_status="BLOCKED",
                attempt_number=payment.retry_count,
                started_at=now,
                completed_at=now,
                error_code="MAX_RETRIES_EXCEEDED",
                error_message=f"Attempt limit of {max_allowed} exhausted."
            )
            db.add(rec_action)
            db.commit()

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="ESCALATED",
                actor="RevivePay Invariant Supervisor",
                notes=f"Invariant enforced: retry_count ({payment.retry_count}) >= max_retries ({max_allowed}). Escalated."
            )
            return {
                "success": False,
                "status": "ESCALATED",
                "action_id": action_id,
                "recovered_amount": 0.0,
                "message": f"Maximum allowed retries ({max_allowed}) reached. Safely escalated."
            }

        # Commencing valid execution
        case.execution_status = "EXECUTING"
        RecoveryStateMachine.transition(
            db=db,
            case=case,
            to_state="EXECUTING",
            actor=actor,
            notes=f"Commencing dispatch of recovery action: {action}"
        )

        # Domain Entity: RecoveryAction
        rec_action = RecoveryAction(
            action_id=action_id,
            case_id=case.case_id,
            action_type=action,
            requested_by=actor,
            policy_decision=case.policy_status,
            execution_status="EXECUTING",
            attempt_number=(payment.retry_count if payment else 0) + 1,
            started_at=now
        )
        db.add(rec_action)
        db.commit()

        # Dispatch action
        if action == "retry_payment":
            payment.retry_count = min(payment.retry_count + 1, max_allowed)
            
            # Canonical Event: recovery.action.executed
            AuditService.log_event(
                db=db,
                case_id=case.case_id,
                actor=actor,
                action=RecoveryEventType.ACTION_EXECUTED.value,
                actor_type="OPERATOR" if "Operator" in actor else "SYSTEM",
                input_data={"action_id": action_id, "action": "retry_payment", "amount": payment.amount},
                policy_result="PASSED",
                notes=f"Executing payment retry attempt {payment.retry_count} of {max_allowed}"
            )

            success, rzp_pay_id, gateway_resp = RazorpayService.simulate_payment_retry(
                payment_id=payment.payment_id,
                amount=payment.amount,
                failure_category=payment.failure_category
            )

            if success:
                payment.status = "SUCCESS"
                payment.provider_payment_id = rzp_pay_id
                
                case.execution_status = "COMPLETED"
                case.recovered_amount = payment.amount
                case.outcome_verified = True
                case.resolved_at = datetime.datetime.utcnow()
                if customer:
                    customer.total_successful_payments += 1
                    customer.lifetime_value += payment.amount
                    customer.last_successful_payment_at = datetime.datetime.utcnow()

                rec_action.execution_status = "COMPLETED"
                rec_action.provider_reference = rzp_pay_id
                rec_action.completed_at = datetime.datetime.utcnow()

                # Progression: EXECUTING -> VERIFYING -> RECOVERED
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="VERIFYING",
                    actor="Razorpay Test Gateway",
                    notes=f"Payment captured (Ref: {rzp_pay_id}). Verifying settlement and ledger."
                )
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="RECOVERED",
                    actor="RevivePay Outcome Verifier",
                    notes=f"Payment of ₹{payment.amount:,.2f} successfully verified, settled, and ledger recorded."
                )

                # Broadcast live telemetry event
                notify_live_event("payment_recovered", {
                    "case_id": case.case_id,
                    "amount": payment.amount,
                    "customer_name": customer.name if customer else "Enterprise Customer",
                    "payment_id": rzp_pay_id,
                    "status": "RECOVERED"
                })

                return {
                    "success": True,
                    "status": "RECOVERED",
                    "action_id": action_id,
                    "recovered_amount": payment.amount,
                    "outcome_verified": True,
                    "message": f"Payment successfully recovered: ₹{payment.amount:,.2f}"
                }
            else:
                rec_action.execution_status = "FAILED"
                rec_action.completed_at = datetime.datetime.utcnow()
                rec_action.error_code = "GATEWAY_DECLINE"
                rec_action.error_message = "Retry request declined by issuer gateway."

                # Failure Progression: EXECUTING -> FAILED -> REASSESS -> STOPPED / ESCALATED
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="FAILED",
                    actor="Razorpay Gateway Client",
                    notes="Payment retry declined by issuer gateway."
                )
                RecoveryStateMachine.transition(
                    db=db,
                    case=case,
                    to_state="REASSESS",
                    actor="RevivePay Autonomous Supervisor",
                    notes="Reassessing failure telemetry, customer liquidity windows, and retry limits."
                )

                if payment.retry_count >= max_allowed:
                    case.execution_status = "FAILED"
                    case.outcome_verified = False
                    case.recovered_amount = 0.0
                    case.resolved_at = datetime.datetime.utcnow()

                    final_state = "ESCALATED" if (payment.amount >= 20000 or (customer and customer.account_tier in ["VIP", "ENTERPRISE"])) else "STOPPED"
                    RecoveryStateMachine.transition(
                        db=db,
                        case=case,
                        to_state=final_state,
                        actor="RevivePay Safety Supervisor",
                        notes=f"Max retries ({max_allowed}) exhausted. Case transitioned to {final_state}."
                    )
                else:
                    RecoveryStateMachine.transition(
                        db=db,
                        case=case,
                        to_state="ACTION_RECOMMENDED",
                        actor="RevivePay Autonomous Supervisor",
                        notes=f"Alternative retry window recommended (attempt {payment.retry_count}/{max_allowed})."
                    )

                return {
                    "success": False,
                    "status": case.recovery_status,
                    "action_id": action_id,
                    "recovered_amount": 0.0,
                    "outcome_verified": False,
                    "message": "Payment retry failed at gateway. Case updated."
                }

        elif action == "create_payment_link":
            link_data = RazorpayService.create_payment_link(
                amount=payment.amount,
                currency=payment.currency,
                customer_name=customer.name,
                customer_email=customer.email,
                description=f"Recovery link for {payment.payment_id}"
            )
            case.execution_status = "COMPLETED"
            rec_action.execution_status = "COMPLETED"
            rec_action.provider_reference = link_data.get("id")
            rec_action.completed_at = datetime.datetime.utcnow()

            # Domain Entity: Notification
            notif = Notification(
                notification_id=f"notif_{uuid.uuid4().hex[:12]}",
                case_id=case.case_id,
                customer_id=customer.customer_id,
                channel="email",
                template="payment_recovery_link_v1",
                message=f"Recovery link generated: {link_data.get('short_url')}",
                status="DELIVERED",
                provider_reference=link_data.get("id"),
                sent_at=datetime.datetime.utcnow()
            )
            db.add(notif)

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="ACTION_RECOMMENDED",
                actor="RevivePay Payment Link Service",
                notes=f"Generated recovery link: {link_data.get('short_url')}"
            )
            return {
                "success": True,
                "status": "ACTION_RECOMMENDED",
                "action_id": action_id,
                "recovered_amount": 0.0,
                "message": f"Payment recovery link created: {link_data.get('short_url')}"
            }

        elif action in ["send_customer_notification", "trigger_checkout_reminder", "request_payment_method_update"]:
            case.execution_status = "COMPLETED"
            rec_action.execution_status = "COMPLETED"
            rec_action.completed_at = datetime.datetime.utcnow()

            notif = Notification(
                notification_id=f"notif_{uuid.uuid4().hex[:12]}",
                case_id=case.case_id,
                customer_id=customer.customer_id,
                channel="email",
                template="customer_recovery_prompt_v1",
                message=f"Dispatched {action} to {customer.email}",
                status="DELIVERED",
                sent_at=datetime.datetime.utcnow()
            )
            db.add(notif)

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="ACTION_RECOMMENDED",
                actor="RevivePay Notification Engine",
                notes=f"Customer dispatched '{action}' communication."
            )
            return {
                "success": True,
                "status": "ACTION_RECOMMENDED",
                "action_id": action_id,
                "recovered_amount": 0.0,
                "message": f"Customer recovery action '{action}' dispatched."
            }

        elif action == "stop_recovery":
            case.execution_status = "COMPLETED"
            rec_action.execution_status = "COMPLETED"
            rec_action.completed_at = datetime.datetime.utcnow()

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="STOPPED",
                actor=actor,
                notes=f"Recovery process terminated by {actor}."
            )
            return {
                "success": True,
                "status": "STOPPED",
                "action_id": action_id,
                "recovered_amount": 0.0,
                "message": "Recovery lifecycle stopped."
            }

        else:
            case.execution_status = "COMPLETED"
            rec_action.execution_status = "COMPLETED"
            rec_action.completed_at = datetime.datetime.utcnow()

            RecoveryStateMachine.transition(
                db=db,
                case=case,
                to_state="ESCALATED",
                actor=actor,
                notes=f"Case escalated to merchant operations by {actor}."
            )
            return {
                "success": True,
                "status": "ESCALATED",
                "action_id": action_id,
                "recovered_amount": 0.0,
                "message": "Case escalated to merchant operations."
            }

    @classmethod
    def approve_case(cls, db: Session, case: RecoveryCase, user_name: str, notes: Optional[str] = None) -> RecoveryCase:
        if case.recovery_status == "RECOVERED":
            return case

        case.approval_status = "APPROVED"
        case.approved_by = user_name
        case.updated_at = datetime.datetime.utcnow()

        # Update Approval domain entity
        approval = db.query(Approval).filter(Approval.case_id == case.case_id, Approval.decision == "PENDING").first()
        if approval:
            approval.decision = "APPROVED"
            approval.approved_by = user_name
            approval.decision_reason = notes or "Approved by operator"
            approval.decided_at = datetime.datetime.utcnow()

        # State Machine Progression: AWAITING_APPROVAL -> APPROVED
        RecoveryStateMachine.transition(
            db=db,
            case=case,
            to_state="APPROVED",
            actor=f"Operator ({user_name})",
            actor_type="OPERATOR",
            notes=notes or f"Human operator {user_name} approved recovery action: {case.recommended_action}"
        )

        # Execute approved action (which transitions APPROVED -> EXECUTING -> VERIFYING -> RECOVERED)
        cls.execute_recovery_action(db=db, case=case, actor=f"Operator ({user_name})")
        db.refresh(case)

        notify_live_event("approval_actioned", {
            "case_id": case.case_id,
            "decision": "APPROVED",
            "actor": user_name,
            "customer_name": case.customer.name if case.customer else "Customer",
            "amount": case.amount_at_risk
        })

        return case

    @classmethod
    def reject_case(cls, db: Session, case: RecoveryCase, user_name: str, rejection_reason: str, notes: Optional[str] = None) -> RecoveryCase:
        case.approval_status = "REJECTED"
        case.rejection_reason = rejection_reason
        case.execution_status = "COMPLETED"
        case.outcome_verified = False
        case.recovered_amount = 0.0
        case.resolved_at = datetime.datetime.utcnow()
        case.updated_at = datetime.datetime.utcnow()

        # Update Approval domain entity
        approval = db.query(Approval).filter(Approval.case_id == case.case_id, Approval.decision == "PENDING").first()
        if approval:
            approval.decision = "REJECTED"
            approval.approved_by = user_name
            approval.decision_reason = rejection_reason
            approval.decided_at = datetime.datetime.utcnow()

        # State Machine Progression: AWAITING_APPROVAL -> REJECTED
        RecoveryStateMachine.transition(
            db=db,
            case=case,
            to_state="REJECTED",
            actor=f"Operator ({user_name})",
            actor_type="OPERATOR",
            notes=notes or f"Human operator {user_name} rejected action with reason: {rejection_reason}"
        )
        db.refresh(case)

        notify_live_event("approval_actioned", {
            "case_id": case.case_id,
            "decision": "REJECTED",
            "actor": user_name,
            "customer_name": case.customer.name if case.customer else "Customer",
            "amount": case.amount_at_risk
        })

        return case

    @classmethod
    def check_and_update_tat_statuses(cls, db: Session) -> int:
        """
        Reference implementation of RBI's Turn Around Time and customer compensation framework (RBI/2019-20/67).
        Evaluates open recovery cases against their statutory TAT deadline, flags breaches, calculates
        statutory accrued compensation (₹100/day), and escalates overdue cases to the human approval queue.
        """
        now = datetime.datetime.utcnow()
        open_cases = db.query(RecoveryCase).filter(
            RecoveryCase.recovery_status.notin_(["RECOVERED", "STOPPED", "REJECTED"])
        ).all()
        
        breached_count = 0
        for case in open_cases:
            if not case.tat_deadline:
                case.tat_deadline = case.created_at + datetime.timedelta(days=7)

            if now > case.tat_deadline:
                overdue_seconds = (now - case.tat_deadline).total_seconds()
                days_overdue = max(1, int(overdue_seconds // 86400) + 1)
                compensation = round(days_overdue * 100.0, 2)
                
                was_breached = (case.tat_status == "BREACHED")
                case.tat_status = "BREACHED"
                case.accrued_compensation_inr = compensation
                
                # Auto-escalate to human-in-the-loop review queue regardless of amount
                case.policy_status = "REVIEW_REQUIRED"
                case.approval_required = True
                if case.recovery_status not in ["AWAITING_APPROVAL", "ESCALATED"]:
                    case.recovery_status = "AWAITING_APPROVAL"
                    
                if not was_breached:
                    breached_count += 1
                    AuditService.log_event(
                        db=db,
                        case_id=case.case_id,
                        actor="RBI TAT Policy Monitor",
                        action=RecoveryEventType.TAT_BREACHED.value,
                        notes=f"Statutory TAT deadline breached ({days_overdue}d overdue). Accrued customer compensation: ₹{compensation:,.2f}. Escalated to operator queue."
                    )
            elif (case.tat_deadline - now) <= datetime.timedelta(hours=24):
                case.tat_status = "DUE_TODAY"
            else:
                case.tat_status = "ON_TRACK"

        db.commit()
        return breached_count
