import uuid
import datetime
import random
from typing import Dict, Any, List
from sqlalchemy.orm import Session
from backend.models.all_models import (
    Merchant, Customer, Payment, RecoveryCase, AuditLog, PolicyConfig, Subscription, AbandonedCheckout
)
from backend.events.taxonomy import PaymentEventType, RecoveryEventType, SubscriptionEventType, CheckoutEventType
from backend.services.recovery_engine import RecoveryEngine
from backend.services.audit_service import AuditService

SIM_CUSTOMER_POOL = [
    ("Vikramaditya Sharma", "vikram.sharma"),
    ("Ananya Roy", "ananya.roy"),
    ("Aarav Mehta", "aarav.mehta"),
    ("Pooja Kulkarni", "pooja.kulkarni"),
    ("Vihaan Patel", "vihaan.patel"),
    ("Siddharth Deshmukh", "siddharth.deshmukh"),
    ("Diya Sengupta", "diya.sengupta"),
    ("Reyansh Kapoor", "reyansh.kapoor"),
    ("Pari Verma", "pari.verma"),
    ("Aditya Joshi", "aditya.joshi"),
    ("Ishaan Malhotra", "ishaan.malhotra"),
    ("Meera Iyer", "meera.iyer")
]

class SimulationService:
    @classmethod
    def trigger_scenario(
        cls,
        db: Session,
        scenario: str,
        custom_amount: float = None,
        customer_type: str = "returning",
        payment_method: str = "card"
    ) -> Dict[str, Any]:
        # Ensure default merchant exists
        merchant = db.query(Merchant).first()
        if not merchant:
            merchant = Merchant(
                merchant_id="m_apex_tech_2026",
                name="Apex Cloud Technologies",
                industry="Enterprise Fintech & SaaS"
            )
            db.add(merchant)
            db.commit()
            db.refresh(merchant)

        random_suffix = random.randint(1000, 9999)
        src = "SIMULATION"
        src_desc = "Synthetic event generated by RevivePay"
        
        # Pick randomized customer identity
        c_name, c_handle = random.choice(SIM_CUSTOMER_POOL)
        c_tier = random.choice(["RETURNING", "STANDARD", "VIP", "ENTERPRISE"])
        c_success = random.randint(4, 22)
        c_failed = random.randint(0, 3)
        c_ltv = round(c_success * random.uniform(1500, 12000), 2)
        
        if scenario == "bank_failure" or scenario == "instant_recovery":
            amount = custom_amount or round(random.uniform(2999, 14999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@enterprise.in",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=c_ltv,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            failure_subcodes = [
                ("BANK_DECLINE_TEMPORARY", "Issuer bank switch unavailable (504 timeout)"),
                ("BANK_SWITCH_OUTAGE", "National payment switch packet dropped (502 Gateway Glitch)"),
                ("NETWORK_TIMEOUT", "Authorization node handshake timed out after 8000ms")
            ]
            f_code, f_reason = random.choice(failure_subcodes)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method=payment_method,
                failure_code=f_code,
                failure_reason=f_reason,
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic payment failure event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            if scenario == "instant_recovery" or case.approval_status == "AUTO_APPROVED":
                RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
                db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated temporary bank failure for ₹{amount:,.2f} [SIMULATION].",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "invalid_card":
            amount = custom_amount or round(random.uniform(1499, 8999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@techfirm.co",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=c_ltv,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="CARD_EXPIRED",
                failure_reason="Card token validity expired on network",
                failure_category="card_expired",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic card invalidation event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated card expiration [SIMULATION]. Policy blocked automated retry.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "high_value":
            amount = custom_amount or round(random.uniform(55000, 125000), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Enterprise Client)",
                email=f"{c_handle}.sim{random_suffix}@enterprise.org",
                account_tier="ENTERPRISE",
                total_successful_payments=c_success + 10,
                total_failed_payments=0,
                lifetime_value=350000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="netbanking",
                failure_code="BANK_GATEWAY_TIMEOUT",
                failure_reason="High-value settlement handshake timed out",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated high-value failure of ₹{amount:,.2f} [SIMULATION]. Routed to Human-in-the-Loop review queue.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "subscription_failure":
            amount = custom_amount or round(random.uniform(9999, 29999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (SaaS Mandate)",
                email=f"{c_handle}.sim{random_suffix}@saas.com",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=85000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            sub = Subscription(
                subscription_id=f"sub_sim_{random_suffix}",
                customer_id=cust.customer_id,
                customer_name=cust.name,
                customer_email=cust.email,
                plan_name="Enterprise Monthly Pro",
                amount=amount,
                currency="INR",
                billing_interval="monthly",
                current_status="PAST_DUE",
                retry_count=1,
                max_retries=3,
                failure_reason="Insufficient balance for recurring debit",
                next_retry_at=datetime.datetime.utcnow() + datetime.timedelta(days=1)
            )
            db.add(sub)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Dunning Engine)",
                action=SubscriptionEventType.SUBSCRIPTION_HALTED.value,
                source=src,
                source_description=src_desc,
                decision={"subscription_id": sub.subscription_id, "amount": amount},
                notes="Synthetic subscription recurring billing failure generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "payment_id": f"sub_sim_{random_suffix}",
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 65.0,
                "risk_level": "MEDIUM",
                "root_cause": "Recurring Subscription Insufficient Funds",
                "ai_confidence": 0.89,
                "recommended_action": "schedule_smart_dunning_retry",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated subscription debit failure for ₹{amount:,.2f} [SIMULATION]. Dunning schedule calculated.",
                "audit_events": []
            }

        elif scenario == "checkout_abandonment":
            amount = custom_amount or round(random.uniform(4999, 15999), 2)
            chk = AbandonedCheckout(
                checkout_id=f"chk_sim_{random_suffix}",
                customer_name=f"{c_name} (Cart Dropped)",
                customer_email=f"{c_handle}.sim{random_suffix}@growth.co",
                cart_items=[
                    {"name": "Developer Pro License", "price": round(amount * 0.7, 2)},
                    {"name": "Priority Support Addon", "price": round(amount * 0.3, 2)}
                ],
                total_value=amount,
                currency="INR",
                intent_score=round(random.uniform(88.0, 97.5), 1),
                status="ABANDONED",
                recovery_action="trigger_checkout_reminder"
            )
            db.add(chk)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Cart Engine)",
                action=CheckoutEventType.CHECKOUT_ABANDONED.value,
                source=src,
                source_description=src_desc,
                decision={"checkout_id": chk.checkout_id, "total_value": amount},
                notes="Synthetic abandoned cart event generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "checkout_id": chk.checkout_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 35.0,
                "risk_level": "LOW",
                "root_cause": "Cart Drop with High Purchase Intent",
                "ai_confidence": 0.94,
                "recommended_action": "trigger_checkout_reminder",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated cart abandonment with {chk.intent_score}% intent [SIMULATION].",
                "audit_events": []
            }

        else:  # retry_exhaustion_escalation
            amount = custom_amount or round(random.uniform(3500, 12000), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@consultancy.in",
                account_tier="STANDARD",
                total_successful_payments=3,
                total_failed_payments=2,
                lifetime_value=12000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="BANK_DECLINE",
                failure_reason="Continuous issuer switch timeout",
                failure_category="temporary_bank_failure",
                retry_count=2,  # Already at maximum limit
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            # Trigger action which will encounter max retries invariant
            exec_res = RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
            db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated retry limit exhaustion [SIMULATION]. Case safely escalated.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }
