import uuid
import datetime
import random
from typing import Dict, Any, List
from sqlalchemy.orm import Session
from backend.models.all_models import (
    Merchant, Customer, Payment, RecoveryCase, AuditLog, PolicyConfig, Subscription, AbandonedCheckout
)
from backend.events.taxonomy import PaymentEventType, RecoveryEventType, SubscriptionEventType, CheckoutEventType
from backend.services.recovery_engine import RecoveryEngine
from backend.services.audit_service import AuditService

SIM_CUSTOMER_POOL = [
    ("Vikramaditya Sharma", "vikram.sharma"),
    ("Ananya Roy", "ananya.roy"),
    ("Aarav Mehta", "aarav.mehta"),
    ("Pooja Kulkarni", "pooja.kulkarni"),
    ("Vihaan Patel", "vihaan.patel"),
    ("Siddharth Deshmukh", "siddharth.deshmukh"),
    ("Diya Sengupta", "diya.sengupta"),
    ("Reyansh Kapoor", "reyansh.kapoor"),
    ("Pari Verma", "pari.verma"),
    ("Aditya Joshi", "aditya.joshi"),
    ("Ishaan Malhotra", "ishaan.malhotra"),
    ("Meera Iyer", "meera.iyer")
]

class SimulationService:
    @classmethod
    def trigger_scenario(
        cls,
        db: Session,
        scenario: str,
        custom_amount: float = None,
        customer_type: str = "returning",
        payment_method: str = "card"
    ) -> Dict[str, Any]:
        # Ensure default merchant exists
        merchant = db.query(Merchant).first()
        if not merchant:
            merchant = Merchant(
                merchant_id="m_apex_tech_2026",
                name="Apex Cloud Technologies",
                industry="Enterprise Fintech & SaaS"
            )
            db.add(merchant)
            db.commit()
            db.refresh(merchant)

        random_suffix = random.randint(1000, 9999)
        src = "SIMULATION"
        src_desc = "Synthetic event generated by RevivePay"
        
        # Pick randomized customer identity
        c_name, c_handle = random.choice(SIM_CUSTOMER_POOL)
        c_tier = random.choice(["RETURNING", "STANDARD", "VIP", "ENTERPRISE"])
        c_success = random.randint(4, 22)
        c_failed = random.randint(0, 3)
        c_ltv = round(c_success * random.uniform(1500, 12000), 2)
        
        if scenario == "bank_failure" or scenario == "instant_recovery":
            amount = custom_amount or round(random.uniform(2999, 14999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@enterprise.in",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=c_ltv,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            failure_subcodes = [
                ("BANK_DECLINE_TEMPORARY", "Issuer bank switch unavailable (504 timeout)"),
                ("BANK_SWITCH_OUTAGE", "National payment switch packet dropped (502 Gateway Glitch)"),
                ("NETWORK_TIMEOUT", "Authorization node handshake timed out after 8000ms")
            ]
            f_code, f_reason = random.choice(failure_subcodes)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method=payment_method,
                failure_code=f_code,
                failure_reason=f_reason,
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic payment failure event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            if scenario == "instant_recovery" or case.approval_status == "AUTO_APPROVED":
                RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
                db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated temporary bank failure for ₹{amount:,.2f} [SIMULATION].",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "invalid_card":
            amount = custom_amount or round(random.uniform(1499, 8999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@techfirm.co",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=c_ltv,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="CARD_EXPIRED",
                failure_reason="Card token validity expired on network",
                failure_category="card_expired",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic card invalidation event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated card expiration [SIMULATION]. Policy blocked automated retry.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "high_value":
            amount = custom_amount or round(random.uniform(55000, 125000), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Enterprise Client)",
                email=f"{c_handle}.sim{random_suffix}@enterprise.org",
                account_tier="ENTERPRISE",
                total_successful_payments=c_success + 10,
                total_failed_payments=0,
                lifetime_value=350000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="netbanking",
                failure_code="BANK_GATEWAY_TIMEOUT",
                failure_reason="High-value settlement handshake timed out",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated high-value failure of ₹{amount:,.2f} [SIMULATION]. Routed to Human-in-the-Loop review queue.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "subscription_failure":
            amount = custom_amount or round(random.uniform(9999, 29999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (SaaS Mandate)",
                email=f"{c_handle}.sim{random_suffix}@saas.com",
                account_tier=c_tier,
                total_successful_payments=c_success,
                total_failed_payments=c_failed,
                lifetime_value=85000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            sub = Subscription(
                subscription_id=f"sub_sim_{random_suffix}",
                customer_id=cust.customer_id,
                customer_name=cust.name,
                customer_email=cust.email,
                plan_name="Enterprise Monthly Pro",
                amount=amount,
                currency="INR",
                billing_interval="monthly",
                current_status="PAST_DUE",
                retry_count=1,
                max_retries=3,
                failure_reason="Insufficient balance for recurring debit",
                next_retry_at=datetime.datetime.utcnow() + datetime.timedelta(days=1)
            )
            db.add(sub)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Dunning Engine)",
                action=SubscriptionEventType.SUBSCRIPTION_HALTED.value,
                source=src,
                source_description=src_desc,
                decision={"subscription_id": sub.subscription_id, "amount": amount},
                notes="Synthetic subscription recurring billing failure generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "payment_id": f"sub_sim_{random_suffix}",
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 65.0,
                "risk_level": "MEDIUM",
                "root_cause": "Recurring Subscription Insufficient Funds",
                "ai_confidence": 0.89,
                "recommended_action": "schedule_smart_dunning_retry",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated subscription debit failure for ₹{amount:,.2f} [SIMULATION]. Dunning schedule calculated.",
                "audit_events": []
            }

        elif scenario == "checkout_abandonment":
            amount = custom_amount or round(random.uniform(4999, 15999), 2)
            chk = AbandonedCheckout(
                checkout_id=f"chk_sim_{random_suffix}",
                customer_name=f"{c_name} (Cart Dropped)",
                customer_email=f"{c_handle}.sim{random_suffix}@growth.co",
                cart_items=[
                    {"name": "Developer Pro License", "price": round(amount * 0.7, 2)},
                    {"name": "Priority Support Addon", "price": round(amount * 0.3, 2)}
                ],
                total_value=amount,
                currency="INR",
                intent_score=round(random.uniform(88.0, 97.5), 1),
                status="ABANDONED",
                recovery_action="trigger_checkout_reminder"
            )
            db.add(chk)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Cart Engine)",
                action=CheckoutEventType.CHECKOUT_ABANDONED.value,
                source=src,
                source_description=src_desc,
                decision={"checkout_id": chk.checkout_id, "total_value": amount},
                notes="Synthetic abandoned cart event generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "checkout_id": chk.checkout_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 35.0,
                "risk_level": "LOW",
                "root_cause": "Cart Drop with High Purchase Intent",
                "ai_confidence": 0.94,
                "recommended_action": "trigger_checkout_reminder",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated cart abandonment with {chk.intent_score}% intent [SIMULATION].",
                "audit_events": []
            }

        elif scenario in ["retry_exhaustion_escalation", "retry_exhaustion", "escalation"]:
            amount = custom_amount or round(random.uniform(3500, 12000), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated)",
                email=f"{c_handle}.sim{random_suffix}@consultancy.in",
                account_tier="STANDARD",
                total_successful_payments=3,
                total_failed_payments=2,
                lifetime_value=12000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="BANK_DECLINE",
                failure_reason="Continuous issuer switch timeout",
                failure_category="temporary_bank_failure",
                retry_count=2,  # Already at maximum limit
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            # Trigger action which will encounter max retries invariant
            exec_res = RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
            db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated retry limit exhaustion [SIMULATION]. Case safely escalated.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario in ["policy_override", "policy_override_high_value", "policy_override_scenario"]:
            # B.1: Demonstrates AI being overruled by deterministic policy
            amount = custom_amount or 38500.0  # Exceeds ₹10,000 automated action limit
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Simulated High-Value)",
                email=f"{c_handle}.sim{random_suffix}@fintechcorp.in",
                account_tier="ENTERPRISE",
                total_successful_payments=18,
                total_failed_payments=1,
                lifetime_value=185000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="BANK_SWITCH_OUTAGE",
                failure_reason="Issuer bank gateway timeout (504)",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )
            
            # Record explicit policy override audit event
            now_dt = datetime.datetime.utcnow()
            override_msg = "AI recommended auto-retry (94% confidence) — blocked by policy: exceeds ₹10,000 automated-action limit. Routed to Human-in-the-Loop regardless of model confidence."
            db.add(AuditLog(
                audit_id=f"aud_pol_ovr_{case.case_id}_{int(now_dt.timestamp())}",
                case_id=case.case_id,
                event_type=RecoveryEventType.POLICY_OVERRODE_AI.value,
                actor_type="GATEWAY",
                actor_id="Deterministic Policy Gateway",
                timestamp=now_dt,
                policy_result="REVIEW_REQUIRED",
                execution_result="PENDING_HUMAN_APPROVAL",
                decision={
                    "ai_proposed_action": "retry_payment",
                    "ai_confidence": 0.94,
                    "policy_decision": "REVIEW_REQUIRED",
                    "rule_triggered": "MAX_AUTOMATED_AMOUNT_EXCEEDED",
                    "threshold_inr": 10000.0,
                    "transaction_amount_inr": amount
                },
                notes=override_msg,
                actor="Deterministic Policy Gateway",
                action=RecoveryEventType.POLICY_OVERRODE_AI.value
            ))
            db.commit()
            db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": "temporary_bank_failure",
                "ai_confidence": 0.94,
                "recommended_action": "retry_payment",
                "policy_status": "REVIEW_REQUIRED",
                "recovery_status": "AWAITING_APPROVAL",
                "overrode_ai_recommendation": True,
                "ai_original_recommendation": "retry_payment (94% confidence)",
                "ai_override_reason": override_msg,
                "message": f"Successfully simulated Policy Override: ₹{amount:,.2f} order routed to Human Review despite 94% AI confidence.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario in ["gemini_fallback", "gemini_fallback_test", "force_fallback"]:
            # B.2: Demonstrates forced failover to Gemini 1.5 Pro
            amount = custom_amount or round(random.uniform(4999, 24999), 2)
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name=f"{c_name} (Gemini Fallback Test)",
                email=f"{c_handle}.gemini{random_suffix}@enterprise.in",
                account_tier="VIP",
                total_successful_payments=9,
                total_failed_payments=1,
                lifetime_value=45000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="upi",
                failure_code="ISSUER_NODE_TIMEOUT_504",
                failure_reason="Primary issuer node unresponsive after 3500ms",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )
            
            # Emulate fallback model attribution on AgentDecision
            agent_dec = case.agent_decisions[0] if case.agent_decisions else None
            if agent_dec:
                agent_dec.model_provider = "google"
                agent_dec.model_name = "gemini-1.5-pro (fallback — primary provider timeout)"
            else:
                db.add(AgentDecision(
                    decision_id=f"dec_gemini_{case.case_id}",
                    case_id=case.case_id,
                    model_provider="google",
                    model_name="gemini-1.5-pro (fallback — primary provider timeout)",
                    root_cause=case.root_cause or "temporary_bank_failure",
                    confidence=case.ai_confidence or 0.92,
                    recommended_action=case.recommended_action or "retry_payment"
                ))
            db.commit()
            db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "model_name": "gemini-1.5-pro (fallback — primary provider timeout)",
                "message": f"Successfully simulated Multi-Tier Fallback: Primary Claude timed out (>3500ms); reasoning generated by Gemini 1.5 Pro.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario in ["chaos_tampered_webhook", "tampered_signature", "chaos_test"]:
            # C.1: Chaos test sending a forged webhook signature
            from backend.events.taxonomy import WebhookEventType
            amount = custom_amount or 19999.0
            now_dt = datetime.datetime.utcnow()
            audit_id = f"aud_chaos_rej_{int(now_dt.timestamp())}_{random_suffix}"
            notes_str = "⚠️ Webhook rejected: HMAC-SHA256 signature verification failed (forged signature detected) — payload discarded, no case created."
            
            db.add(AuditLog(
                audit_id=audit_id,
                case_id="WEBHOOK-INGRESS",
                event_type=WebhookEventType.WEBHOOK_VERIFICATION_REJECTED.value,
                actor_type="GATEWAY",
                actor_id="Razorpay HMAC-SHA256 Gateway",
                actor="Razorpay HMAC-SHA256 Gateway",
                action=WebhookEventType.WEBHOOK_VERIFICATION_REJECTED.value,
                timestamp=now_dt,
                policy_result="BLOCKED",
                execution_result="REJECTED_401",
                decision={
                    "security_defense": True,
                    "simulated_chaos_test": True,
                    "signature_verified": False,
                    "http_status": 401,
                    "action_taken": "PAYLOAD_DISCARDED_NO_CASE_CREATED"
                },
                notes=notes_str
            ))
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "payment_id": None,
                "source": "SIMULATION",
                "source_description": "Security Chaos Ingress Test",
                "status": "REJECTED_401",
                "risk_score": 100.0,
                "risk_level": "CRITICAL",
                "root_cause": "FORGED_HMAC_SIGNATURE_REJECTED",
                "ai_confidence": 1.0,
                "recommended_action": "stop_recovery",
                "policy_status": "BLOCKED",
                "recovery_status": "STOPPED",
                "message": notes_str,
                "audit_events": [
                    {
                        "actor": "Razorpay HMAC-SHA256 Gateway",
                        "action": WebhookEventType.WEBHOOK_VERIFICATION_REJECTED.value,
                        "timestamp": now_dt.isoformat(),
                        "notes": notes_str
                    }
                ]
            }

        else:
            # Default fallback scenario
            return cls.trigger_scenario(db, "bank_failure", custom_amount, customer_type, payment_method)
