import uuid
import datetime
import random
from typing import Dict, Any, List
from sqlalchemy.orm import Session
from backend.models.all_models import (
    Merchant, Customer, Payment, RecoveryCase, AuditLog, PolicyConfig, Subscription, AbandonedCheckout
)
from backend.events.taxonomy import PaymentEventType, RecoveryEventType, SubscriptionEventType, CheckoutEventType
from backend.services.recovery_engine import RecoveryEngine
from backend.services.audit_service import AuditService

class SimulationService:
    @classmethod
    def trigger_scenario(
        cls,
        db: Session,
        scenario: str,
        custom_amount: float = None,
        customer_type: str = "returning",
        payment_method: str = "card"
    ) -> Dict[str, Any]:
        # Ensure default merchant exists
        merchant = db.query(Merchant).first()
        if not merchant:
            merchant = Merchant(
                merchant_id="m_apex_tech_2026",
                name="Apex Cloud Technologies",
                industry="Enterprise Fintech & SaaS"
            )
            db.add(merchant)
            db.commit()
            db.refresh(merchant)

        random_suffix = random.randint(1000, 9999)
        src = "SIMULATION"
        src_desc = "Synthetic event generated by RevivePay"
        
        if scenario == "bank_failure" or scenario == "instant_recovery":
            amount = custom_amount or 4999.0
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name="Vikramaditya Sharma (Simulated)",
                email="vikram.sharma.sim@enterprise.in",
                account_tier="RETURNING",
                total_successful_payments=8,
                total_failed_payments=1,
                lifetime_value=48500.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method=payment_method,
                failure_code="BANK_DECLINE_TEMPORARY",
                failure_reason="Issuer bank switch unavailable (504 timeout)",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic payment failure event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            if scenario == "instant_recovery" or case.approval_status == "AUTO_APPROVED":
                RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
                db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated temporary bank failure for ₹{amount:,.2f} [SIMULATION].",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "invalid_card":
            amount = custom_amount or 2499.0
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name="Ananya Roy (Simulated)",
                email="ananya.roy.sim@techfirm.co",
                account_tier="STANDARD",
                total_successful_payments=2,
                total_failed_payments=1,
                lifetime_value=5000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="CARD_EXPIRED",
                failure_reason="Card token validity expired on network",
                failure_category="card_expired",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center",
                action=PaymentEventType.PAYMENT_FAILED.value,
                source=src,
                source_description=src_desc,
                input_data={"payment_id": payment.payment_id, "amount": amount, "error": payment.failure_code},
                notes="Synthetic card invalidation event generated by RevivePay Simulation Center."
            )

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated card expiration [SIMULATION]. Policy blocked automated retry.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "high_value":
            amount = custom_amount or 85000.0
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name="Aarav Mehta (Enterprise Client)",
                email="aarav.mehta.sim@enterprise.org",
                account_tier="ENTERPRISE",
                total_successful_payments=15,
                total_failed_payments=0,
                lifetime_value=250000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="netbanking",
                failure_code="BANK_GATEWAY_TIMEOUT",
                failure_reason="High-value settlement handshake timed out",
                failure_category="temporary_bank_failure",
                retry_count=0,
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated high-value failure of ₹{amount:,.2f} [SIMULATION]. Routed to Human-in-the-Loop review queue.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }

        elif scenario == "subscription_failure":
            amount = custom_amount or 14999.0
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name="Pooja Kulkarni (Simulated SaaS)",
                email="pooja.kulkarni.sim@saas.com",
                account_tier="RETURNING",
                total_successful_payments=6,
                total_failed_payments=1,
                lifetime_value=75000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            sub = Subscription(
                subscription_id=f"sub_sim_{random_suffix}",
                customer_id=cust.customer_id,
                customer_name=cust.name,
                customer_email=cust.email,
                plan_name="Enterprise Monthly Pro",
                amount=amount,
                currency="INR",
                billing_interval="monthly",
                current_status="PAST_DUE",
                retry_count=1,
                max_retries=3,
                failure_reason="Insufficient balance for recurring debit",
                next_retry_at=datetime.datetime.utcnow() + datetime.timedelta(days=1)
            )
            db.add(sub)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Dunning Engine)",
                action=SubscriptionEventType.SUBSCRIPTION_HALTED.value,
                source=src,
                source_description=src_desc,
                decision={"subscription_id": sub.subscription_id, "amount": amount},
                notes="Synthetic subscription recurring billing failure generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "payment_id": f"sub_sim_{random_suffix}",
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 65.0,
                "risk_level": "MEDIUM",
                "root_cause": "Recurring Subscription Insufficient Funds",
                "ai_confidence": 0.89,
                "recommended_action": "schedule_smart_dunning_retry",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated subscription debit failure for ₹{amount:,.2f} [SIMULATION]. Dunning schedule calculated.",
                "audit_events": []
            }

        elif scenario == "checkout_abandonment":
            amount = custom_amount or 6999.0
            chk = AbandonedCheckout(
                checkout_id=f"chk_sim_{random_suffix}",
                customer_name="Vihaan Patel (Simulated)",
                customer_email="vihaan.patel.sim@growth.co",
                cart_items=[
                    {"name": "Developer Pro License", "price": 4999.0},
                    {"name": "Priority Support Addon", "price": 2000.0}
                ],
                total_value=amount,
                currency="INR",
                intent_score=92.5,
                status="ABANDONED",
                recovery_action="trigger_checkout_reminder"
            )
            db.add(chk)

            AuditService.log_event(
                db=db,
                case_id=None,
                actor="Simulation Center (Cart Engine)",
                action=CheckoutEventType.CHECKOUT_ABANDONED.value,
                source=src,
                source_description=src_desc,
                decision={"checkout_id": chk.checkout_id, "total_value": amount},
                notes="Synthetic abandoned cart event generated by RevivePay Simulation Center."
            )
            db.commit()

            return {
                "scenario": scenario,
                "case_id": None,
                "checkout_id": chk.checkout_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": 35.0,
                "risk_level": "LOW",
                "root_cause": "Cart Drop with High Purchase Intent",
                "ai_confidence": 0.94,
                "recommended_action": "trigger_checkout_reminder",
                "policy_status": "PASSED",
                "recovery_status": "ACTION_RECOMMENDED",
                "message": f"Successfully simulated cart abandonment with 92.5% intent [SIMULATION].",
                "audit_events": []
            }

        else:  # retry_exhaustion_escalation
            amount = custom_amount or 6200.0
            cust = Customer(
                customer_id=f"cust_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                external_customer_id=f"cust_ext_sim_{random_suffix}",
                name="Siddharth Deshmukh (Simulated)",
                email="siddharth.sim@consultancy.in",
                account_tier="STANDARD",
                total_successful_payments=3,
                total_failed_payments=2,
                lifetime_value=12000.0,
                consent_status=True
            )
            db.add(cust)
            db.commit()
            db.refresh(cust)

            payment = Payment(
                payment_id=f"pay_sim_{random_suffix}",
                merchant_id=merchant.merchant_id,
                customer_id=cust.customer_id,
                provider="simulation_engine",
                amount=amount,
                currency="INR",
                status="FAILED",
                payment_method="card",
                failure_code="BANK_DECLINE",
                failure_reason="Continuous issuer switch timeout",
                failure_category="temporary_bank_failure",
                retry_count=2,  # Already at maximum limit
                max_retry_count=2,
                source=src,
                source_description=src_desc
            )
            db.add(payment)
            db.commit()
            db.refresh(payment)

            case = RecoveryEngine.process_payment_failure(
                db=db,
                payment=payment,
                customer=cust,
                merchant=merchant
            )

            # Trigger action which will encounter max retries invariant
            exec_res = RecoveryEngine.execute_recovery_action(db=db, case=case, actor="RevivePay Autonomous Engine")
            db.refresh(case)

            return {
                "scenario": scenario,
                "case_id": case.case_id,
                "payment_id": payment.payment_id,
                "source": "SIMULATION",
                "source_description": "Synthetic event generated by RevivePay",
                "status": "SUCCESS",
                "risk_score": case.risk_score,
                "risk_level": case.risk_level,
                "root_cause": case.root_cause,
                "ai_confidence": case.ai_confidence,
                "recommended_action": case.recommended_action,
                "policy_status": case.policy_status,
                "recovery_status": case.recovery_status,
                "message": f"Successfully simulated retry limit exhaustion [SIMULATION]. Case safely escalated.",
                "audit_events": [
                    {"actor": log.actor, "action": log.action, "timestamp": log.timestamp.isoformat(), "notes": log.notes}
                    for log in case.audit_logs
                ]
            }
