from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session
from backend.database import get_db
from backend.models.all_models import RecoveryCase, Payment, Customer, Merchant, User, AgentDecision
from backend.schemas.all_schemas import (
    RecoveryCaseResponse, RecoveryApprovalRequest, RecoveryExecutionResponse
)
from backend.services.recovery_engine import RecoveryEngine
from backend.config import settings
from backend.services.auth_service import require_role, verify_step_up_token

router = APIRouter(prefix="/recovery", tags=["Recovery Cases"])

OPERATOR_ROLES = ["ADMIN", "REVENUE_OPERATOR", "MERCHANT_OWNER"]

def map_case_response(case: RecoveryCase, db: Session) -> dict:
    cust = db.query(Customer).filter(Customer.customer_id == case.customer_id).first()
    pay = db.query(Payment).filter(Payment.payment_id == case.payment_id).first()
    agent_dec = db.query(AgentDecision).filter(AgentDecision.case_id == case.case_id).order_by(AgentDecision.decision_timestamp.desc()).first()
    return {
        "id": case.case_id,
        "case_id": case.case_id,
        "payment_id": case.payment_id,
        "payment_code": pay.payment_id if pay else "UNKNOWN",
        "customer_id": case.customer_id,
        "customer_name": cust.name if cust else "Unknown Customer",
        "customer_email": cust.email if cust else "unknown@email.com",
        "customer_tier": cust.account_tier if cust else "STANDARD",
        "source": case.source or "RAZORPAY_TEST",
        "source_description": case.source_description or ("Synthetic event generated by RevivePay" if case.source == "SIMULATION" else "Event received from Razorpay Test environment"),
        "case_type": case.case_type or "PAYMENT_FAILURE",
        "amount": case.amount_at_risk,
        "amount_at_risk": case.amount_at_risk,
        "currency": case.currency or "INR",
        "failure_type": case.failure_type or case.root_cause or "BANK_DECLINE",
        "risk_score": case.risk_score,
        "risk_level": case.risk_level,
        "risk_factors": case.risk_factors or {},
        "root_cause": case.root_cause,
        "ai_confidence": case.ai_confidence,
        "evidence": case.evidence or [],
        "recommended_action": case.recommended_action,
        "reasoning_summary": case.reasoning_summary,
        "policy_status": case.policy_status,
        "policy_checklist": case.policy_checklist or [],
        "approval_required": case.approval_required,
        "approval_status": case.approval_status,
        "rejection_reason": case.rejection_reason,
        "approved_by": case.approved_by,
        "execution_status": case.execution_status,
        "recovery_status": case.recovery_status,
        "outcome_verified": case.outcome_verified,
        "recovered_amount": case.recovered_amount,
        "tat_deadline": case.tat_deadline,
        "tat_status": case.tat_status or "ON_TRACK",
        "accrued_compensation_inr": case.accrued_compensation_inr or 0.0,
        "model_provider": agent_dec.model_provider if agent_dec else "deterministic_rules_engine",
        "model_name": agent_dec.model_name if agent_dec else "rules-engine-v2.1",
        "overrode_ai_recommendation": (case.amount_at_risk > 10000.0 and case.approval_required and case.policy_status == "REVIEW_REQUIRED"),
        "ai_original_recommendation": f"{case.recommended_action} ({int((case.ai_confidence or 0.94)*100)}% confidence)",
        "ai_override_reason": f"AI recommended auto-retry ({int((case.ai_confidence or 0.94)*100)}% confidence) — blocked by policy: exceeds ₹10,000 automated-action limit. Routed to Human-in-the-Loop regardless of model confidence.",
        "raw_prompt": agent_dec.prompt_raw if agent_dec else None,
        "raw_response": agent_dec.response_raw if agent_dec else None,
        "created_at": case.created_at,
        "updated_at": case.updated_at,
        "resolved_at": case.resolved_at
    }

@router.get("/count")
def get_recovery_cases_count(db: Session = Depends(get_db)):
    """Returns the single canonical total count of all recovery cases in the registry."""
    return {"total_cases": db.query(RecoveryCase).count()}

@router.get("/cases", response_model=List[RecoveryCaseResponse])
def get_recovery_cases(
    status: Optional[str] = None,
    risk_level: Optional[str] = None,
    approval_status: Optional[str] = None,
    search: Optional[str] = None,
    limit: int = 1000,
    offset: int = 0,
    db: Session = Depends(get_db)
):
    query = db.query(RecoveryCase)
    
    if status and status != "ALL":
        query = query.filter(RecoveryCase.recovery_status == status)
    if risk_level and risk_level != "ALL":
        query = query.filter(RecoveryCase.risk_level == risk_level)
    if approval_status and approval_status != "ALL":
        query = query.filter(RecoveryCase.approval_status == approval_status)
    if search:
        search_fmt = f"%{search}%"
        query = query.join(Customer, isouter=True).filter(
            (RecoveryCase.case_id.ilike(search_fmt)) |
            (RecoveryCase.failure_type.ilike(search_fmt)) |
            (Customer.name.ilike(search_fmt))
        )
        
    cases = query.order_by(RecoveryCase.created_at.desc()).offset(offset).limit(limit).all()
    return [map_case_response(c, db) for c in cases]

@router.get("/cases/{case_id}", response_model=RecoveryCaseResponse)
def get_recovery_case_detail(case_id: str, db: Session = Depends(get_db)):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail=f"Recovery case '{case_id}' not found")
    return map_case_response(case, db)

@router.post("/{case_id}/analyze", response_model=RecoveryCaseResponse)
def reanalyze_case(case_id: str, db: Session = Depends(get_db)):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    
    payment = case.payment
    customer = case.customer
    merchant = payment.merchant
    
    updated_case = RecoveryEngine.process_payment_failure(
        db=db,
        payment=payment,
        customer=customer,
        merchant=merchant
    )
    return map_case_response(updated_case, db)

@router.post("/{case_id}/approve", response_model=RecoveryCaseResponse)
def approve_case(
    case_id: str,
    req: RecoveryApprovalRequest,
    current_user: User = Depends(require_role(OPERATOR_ROLES)),
    db: Session = Depends(get_db)
):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    
    # Enforce Step-Up Re-Authentication for High-Value Cases (>= ₹50,000)
    if case.amount_at_risk >= settings.HIGH_VALUE_THRESHOLD:
        if not req.step_up_token or not verify_step_up_token(req.step_up_token, current_user, case_id):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Enterprise Governance Rule: Case amount ₹{case.amount_at_risk:,.2f} exceeds high-value threshold (₹{settings.HIGH_VALUE_THRESHOLD:,.2f}). Step-up re-authentication is required before approval."
            )

    updated_case = RecoveryEngine.approve_case(
        db=db,
        case=case,
        user_name=current_user.name or "Senior Revenue Operator",
        notes=req.notes
    )
    return map_case_response(updated_case, db)

@router.post("/{case_id}/reject", response_model=RecoveryCaseResponse)
def reject_case(
    case_id: str,
    req: RecoveryApprovalRequest,
    current_user: User = Depends(require_role(OPERATOR_ROLES)),
    db: Session = Depends(get_db)
):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    
    reason = req.rejection_reason or "Declined by operator"
    updated_case = RecoveryEngine.reject_case(
        db=db,
        case=case,
        user_name=current_user.name or "Senior Revenue Operator",
        rejection_reason=reason,
        notes=req.notes
    )
    return map_case_response(updated_case, db)

@router.post("/{case_id}/execute", response_model=RecoveryExecutionResponse)
def execute_case(
    case_id: str,
    current_user: User = Depends(require_role(OPERATOR_ROLES)),
    db: Session = Depends(get_db)
):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    
    result = RecoveryEngine.execute_recovery_action(
        db=db,
        case=case,
        actor=f"{current_user.name} ({current_user.role})"
    )
    return {
        "case_id": case.case_id,
        "status": case.recovery_status,
        "action_executed": case.recommended_action,
        "execution_result": result.get("status", "COMPLETED"),
        "recovered_amount": result.get("recovered_amount", 0.0),
        "message": result.get("message", "Execution finished.")
    }

@router.post("/{case_id}/stop", response_model=RecoveryCaseResponse)
def stop_case(
    case_id: str,
    current_user: User = Depends(require_role(OPERATOR_ROLES)),
    db: Session = Depends(get_db)
):
    case = db.query(RecoveryCase).filter(
        RecoveryCase.case_id == case_id
    ).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    
    case.recommended_action = "stop_recovery"
    RecoveryEngine.execute_recovery_action(db=db, case=case, actor=f"{current_user.name} ({current_user.role})")
    return map_case_response(case, db)

# Direct /cases alias router
cases_router = APIRouter(prefix="/cases", tags=["Cases Direct Access"])

@cases_router.get("/count")
def get_cases_count_direct(db: Session = Depends(get_db)):
    return {"total_cases": db.query(RecoveryCase).count()}

@cases_router.get("", response_model=List[RecoveryCaseResponse])
def get_cases_direct(
    status: Optional[str] = None,
    risk_level: Optional[str] = None,
    approval_status: Optional[str] = None,
    search: Optional[str] = None,
    limit: int = 1000,
    offset: int = 0,
    db: Session = Depends(get_db)
):
    return get_recovery_cases(status, risk_level, approval_status, search, limit, offset, db)

