import React from "react";
import { ShieldAlert, User, CreditCard, Clock, PlayCircle, CheckCircle2, XCircle, CheckCheck, Hash } from "lucide-react";
import { RecoveryCase } from "../../types";
import { RiskBadge } from "../RiskBadge";
import { StatusBadge } from "../StatusBadge";
import { ActionBadge } from "../ActionBadge";
import { EventSourceBadge } from "../EventSourceBadge";

interface CaseDetailsHeroProps {
  caseData: RecoveryCase;
  onExecute: () => void;
  onOpenApproval: () => void;
  isExecuting?: boolean;
}

export const CaseDetailsHero: React.FC<CaseDetailsHeroProps> = ({
  caseData,
  onExecute,
  onOpenApproval,
  isExecuting = false,
}) => {
  const isRecovered = caseData.recovery_status === "RECOVERED";
  const isPendingApproval = caseData.approval_status === "PENDING";
  const isEscalated = caseData.recovery_status === "ESCALATED";

  return (
    <div className="bg-[#0B0F19] border border-slate-800 rounded-xl p-5 shadow-xl relative overflow-hidden">
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 border-b border-slate-800/80 pb-5">
        {/* Case ID & Customer Info */}
        <div className="space-y-1">
          <div className="flex items-center gap-2.5 flex-wrap">
            <span className="font-mono text-xl font-bold text-slate-100 tracking-tight">
              {caseData.case_id}
            </span>
            <EventSourceBadge source={caseData.source} size="md" />
            <RiskBadge level={caseData.risk_level} score={caseData.risk_score} showScore />
            <StatusBadge status={caseData.recovery_status} />
            {caseData.outcome_verified && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 text-[10px] font-mono font-bold">
                <CheckCheck className="w-3 h-3" />
                OUTCOME VERIFIED
              </span>
            )}
            {caseData.approval_required && isPendingApproval && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-amber-500/20 border border-amber-500/40 text-amber-400 text-[10px] font-mono font-bold">
                APPROVAL REQUIRED
              </span>
            )}
          </div>
          <p className="text-[11px] text-slate-400 font-mono">
            {caseData.source_description || (caseData.source === "SIMULATION" ? "Synthetic event generated by RevivePay" : "Event received from Razorpay Test environment")}
          </p>

          <div className="flex flex-wrap items-center gap-4 text-xs text-slate-400 pt-1">
            <div className="flex items-center gap-1.5">
              <User className="w-3.5 h-3.5 text-slate-500" />
              <span className="text-slate-200 font-medium">{caseData.customer_name}</span>
              <span className="text-[10px] px-1.5 py-0.2 rounded bg-slate-800 text-slate-300 font-mono">
                {caseData.customer_tier}
              </span>
            </div>
            <div className="flex items-center gap-1.5 font-mono">
              <CreditCard className="w-3.5 h-3.5 text-slate-500" />
              <span>{caseData.payment_code || caseData.payment_id}</span>
            </div>
            {caseData.execution_id && (
              <div className="flex items-center gap-1 font-mono text-indigo-400">
                <Hash className="w-3 h-3 text-indigo-500" />
                <span>{caseData.execution_id}</span>
              </div>
            )}
            <div className="flex items-center gap-1.5 font-mono text-slate-500">
              <Clock className="w-3.5 h-3.5" />
              <span>{new Date(caseData.created_at).toLocaleTimeString()} IST</span>
            </div>
          </div>
        </div>

        {/* Financial Overview & Action Button */}
        <div className="flex items-center gap-4">
          <div className="text-right">
            <p className="text-[11px] uppercase font-semibold text-slate-500 tracking-wider">Revenue At Risk</p>
            <p className="text-2xl font-mono font-extrabold text-amber-400">
              ₹{(caseData.amount ?? caseData.amount_at_risk ?? 0).toLocaleString()}
            </p>
            {isRecovered && (
              <p className="text-xs font-mono font-semibold text-emerald-400 flex items-center justify-end gap-1">
                <CheckCircle2 className="w-3.5 h-3.5" />
                Recovered: ₹{(caseData.recovered_amount ?? 0).toLocaleString()}
              </p>
            )}
          </div>

          {/* Action Trigger */}
          <div className="pl-3 border-l border-slate-800">
            {isRecovered ? (
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-semibold text-xs">
                <CheckCircle2 className="w-4 h-4" />
                <span>Recovered Successfully</span>
              </div>
            ) : isPendingApproval ? (
              <button
                onClick={onOpenApproval}
                className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 text-slate-950 font-bold text-xs shadow-lg shadow-amber-950/40 transition-all active:scale-95"
              >
                <ShieldAlert className="w-4 h-4" />
                <span>Review & Approve</span>
              </button>
            ) : isEscalated ? (
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-400 font-semibold text-xs">
                <XCircle className="w-4 h-4" />
                <span>Escalated to Operator</span>
              </div>
            ) : (
              <button
                onClick={onExecute}
                disabled={isExecuting}
                className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-500 hover:to-emerald-400 text-white font-bold text-xs shadow-lg shadow-blue-900/40 transition-all active:scale-95 disabled:opacity-50"
              >
                <PlayCircle className="w-4 h-4" />
                <span>{isExecuting ? "Executing Recovery..." : "Execute Recovery Action"}</span>
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Highlights Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-4 text-xs">
        <div className="p-2.5 rounded-lg bg-slate-900/70 border border-slate-800">
          <p className="text-[10px] uppercase font-bold text-slate-500">Failure Code</p>
          <p className="font-mono font-semibold text-rose-400 truncate">{caseData.failure_type}</p>
        </div>
        <div className="p-2.5 rounded-lg bg-slate-900/70 border border-slate-800">
          <p className="text-[10px] uppercase font-bold text-slate-500">AI Recommendation</p>
          <ActionBadge action={caseData.recommended_action} />
        </div>
        <div className="p-2.5 rounded-lg bg-slate-900/70 border border-slate-800">
          <p className="text-[10px] uppercase font-bold text-slate-500">Policy Gate</p>
          <StatusBadge status={caseData.policy_status} type="policy" />
        </div>
        <div className="p-2.5 rounded-lg bg-slate-900/70 border border-slate-800">
          <p className="text-[10px] uppercase font-bold text-slate-500">Approval State</p>
          <StatusBadge status={caseData.approval_status} type="approval" />
        </div>
      </div>
    </div>
  );
};
