import React from "react";
import { ShieldAlert, User, CreditCard, Clock, PlayCircle, CheckCircle2, XCircle, CheckCheck, Hash } from "lucide-react";
import { RecoveryCase } from "../../types";
import { RiskBadge } from "../RiskBadge";
import { StatusBadge } from "../StatusBadge";
import { ActionBadge } from "../ActionBadge";
import { EventSourceBadge } from "../EventSourceBadge";
import { formatINR } from "../../data/mockData";
import { formatTimeSafe } from "../../utils/dateUtils";

interface CaseDetailsHeroProps {
  caseData: RecoveryCase;
  onExecute: () => void;
  onOpenApproval: () => void;
  isExecuting?: boolean;
}

export const CaseDetailsHero: React.FC<CaseDetailsHeroProps> = ({
  caseData,
  onExecute,
  onOpenApproval,
  isExecuting = false,
}) => {
  const isRecovered = caseData.recovery_status === "RECOVERED";
  const isPendingApproval = caseData.approval_status === "PENDING";
  const isEscalated = caseData.recovery_status === "ESCALATED";

  const amt = caseData.amount ?? caseData.amount_at_risk ?? 0;

  return (
    <div className="bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-2xl p-6 shadow-premium-md relative overflow-hidden font-sans">
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 border-b border-[var(--color-border-subtle)] pb-5">
        {/* Case ID & Customer Info */}
        <div className="space-y-1">
          <div className="flex items-center gap-2.5 flex-wrap">
            <span className="font-mono text-xl font-bold text-[var(--color-text-primary)] tracking-tight">
              {caseData.case_id}
            </span>
            <EventSourceBadge source={caseData.source} size="md" />
            <RiskBadge level={caseData.risk_level} score={caseData.risk_score} showScore />
            <StatusBadge status={caseData.recovery_status} />
            {caseData.outcome_verified && (
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 text-[10px] font-mono font-bold">
                <CheckCheck className="w-3 h-3" />
                OUTCOME VERIFIED
              </span>
            )}
            {caseData.approval_required && isPendingApproval && (
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-600 dark:text-amber-400 text-[10px] font-mono font-bold">
                APPROVAL REQUIRED
              </span>
            )}
          </div>
          <p className="text-[11px] text-[var(--color-text-muted)] font-mono">
            {caseData.source_description || (caseData.source === "SIMULATION" ? "Synthetic event generated by RevivePay" : "Event received from Razorpay Test environment")}
          </p>

          <div className="flex flex-wrap items-center gap-4 text-xs text-[var(--color-text-secondary)] pt-1.5">
            <div className="flex items-center gap-1.5">
              <User className="w-3.5 h-3.5 text-[var(--color-text-muted)]" />
              <span className="text-[var(--color-text-primary)] font-semibold">{caseData.customer_name || "Enterprise Customer"}</span>
              <span className="text-[10px] px-2 py-0.2 rounded-md bg-[var(--color-bg-canvas)] text-[var(--color-text-secondary)] font-mono border border-[var(--color-border-subtle)] font-bold">
                {caseData.customer_tier || "STANDARD"}
              </span>
            </div>
            <div className="flex items-center gap-1.5 font-mono">
              <CreditCard className="w-3.5 h-3.5 text-[var(--color-text-muted)]" />
              <span>{caseData.payment_code || caseData.payment_id || "PAY-UNAVAILABLE"}</span>
            </div>
            {caseData.execution_id && (
              <div className="flex items-center gap-1 font-mono text-[var(--color-accent)] font-semibold">
                <Hash className="w-3 h-3" />
                <span>{caseData.execution_id}</span>
              </div>
            )}
            <div className="flex items-center gap-1.5 font-mono text-[var(--color-text-muted)]">
              <Clock className="w-3.5 h-3.5" />
              <span>{formatTimeSafe(caseData.created_at)} IST</span>
            </div>
          </div>
        </div>

        {/* Financial Overview & Action Button */}
        <div className="flex items-center gap-5">
          <div className="text-right">
            <p className="text-[11px] uppercase font-bold text-[var(--color-text-muted)] tracking-wider font-mono">Revenue At Risk</p>
            <p className="text-2xl font-mono font-extrabold text-amber-600 dark:text-amber-400">
              {formatINR(amt)}
            </p>
            {isRecovered && (
              <p className="text-xs font-mono font-semibold text-emerald-600 dark:text-emerald-400 flex items-center justify-end gap-1">
                <CheckCircle2 className="w-3.5 h-3.5" />
                Recovered: {formatINR(caseData.recovered_amount ?? amt)}
              </p>
            )}
          </div>

          {/* Action Trigger */}
          <div className="pl-4 border-l border-[var(--color-border-subtle)]">
            {isRecovered ? (
              <div className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 font-semibold text-xs">
                <CheckCircle2 className="w-4 h-4" />
                <span>Recovered</span>
              </div>
            ) : isPendingApproval ? (
              <button
                onClick={onOpenApproval}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs shadow-premium-sm transition-all active:scale-95 cursor-pointer"
              >
                <ShieldAlert className="w-4 h-4" />
                <span>Review & Approve</span>
              </button>
            ) : isEscalated ? (
              <div className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-600 dark:text-rose-400 font-semibold text-xs">
                <XCircle className="w-4 h-4" />
                <span>Escalated to Operator</span>
              </div>
            ) : (
              <button
                onClick={onExecute}
                disabled={isExecuting}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold text-xs shadow-premium-sm transition-all active:scale-95 disabled:opacity-50 cursor-pointer"
              >
                <PlayCircle className="w-4 h-4" />
                <span>{isExecuting ? "Executing..." : "Execute Recovery"}</span>
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Highlights Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5 pt-4 text-xs">
        <div className="p-3 rounded-xl bg-[var(--color-bg-canvas)] border border-[var(--color-border-subtle)]">
          <p className="text-[10px] uppercase font-bold text-[var(--color-text-muted)] font-mono">Failure Code</p>
          <p className="font-mono font-semibold text-rose-600 dark:text-rose-400 truncate mt-0.5">{caseData.failure_type || "GATEWAY_TIMEOUT"}</p>
        </div>
        <div className="p-3 rounded-xl bg-[var(--color-bg-canvas)] border border-[var(--color-border-subtle)]">
          <p className="text-[10px] uppercase font-bold text-[var(--color-text-muted)] font-mono mb-1">AI Recommendation</p>
          <ActionBadge action={caseData.recommended_action} />
        </div>
        <div className="p-3 rounded-xl bg-[var(--color-bg-canvas)] border border-[var(--color-border-subtle)]">
          <p className="text-[10px] uppercase font-bold text-[var(--color-text-muted)] font-mono mb-1">Policy Gate</p>
          <StatusBadge status={caseData.policy_status} type="policy" />
        </div>
        <div className="p-3 rounded-xl bg-[var(--color-bg-canvas)] border border-[var(--color-border-subtle)]">
          <p className="text-[10px] uppercase font-bold text-[var(--color-text-muted)] font-mono mb-1">Approval State</p>
          <StatusBadge status={caseData.approval_status} type="approval" />
        </div>
      </div>
    </div>
  );
};
