import React from "react";
import { Zap, FlaskConical } from "lucide-react";

interface EventSourceBadgeProps {
  source?: string;
  showSubtitle?: boolean;
  size?: "sm" | "md" | "lg";
}

export const EventSourceBadge: React.FC<EventSourceBadgeProps> = ({
  source = "RAZORPAY_TEST",
  showSubtitle = false,
  size = "sm"
}) => {
  const isRazorpayTest = source === "RAZORPAY_TEST" || source === "razorpay" || source === "RAZORPAY";

  if (isRazorpayTest) {
    return (
      <div className="inline-flex flex-col items-start gap-0.5">
        <span
          className={`inline-flex items-center gap-1 font-mono font-bold uppercase tracking-wider rounded-full border transition-colors ${
            size === "lg"
              ? "px-3 py-1 text-xs bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/30 shadow-premium-sm"
              : size === "md"
              ? "px-2.5 py-0.5 text-[11px] bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/30"
              : "px-2 py-0.5 text-[10px] bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/30"
          }`}
          title="Event received from Razorpay Test environment"
        >
          <Zap className={`${size === "lg" ? "w-3.5 h-3.5" : "w-3 h-3"} text-indigo-600 dark:text-indigo-400`} />
          <span>Razorpay Test</span>
        </span>
        {showSubtitle && (
          <span className="text-[10px] text-[var(--color-text-secondary)] font-sans">
            Event received from Razorpay Test environment
          </span>
        )}
      </div>
    );
  }

  return (
    <div className="inline-flex flex-col items-start gap-0.5">
      <span
        className={`inline-flex items-center gap-1 font-mono font-bold uppercase tracking-wider rounded-full border transition-colors ${
          size === "lg"
            ? "px-3 py-1 text-xs bg-amber-500/10 text-amber-800 dark:text-amber-300 border-amber-500/30 shadow-premium-sm"
            : size === "md"
            ? "px-2.5 py-0.5 text-[11px] bg-amber-500/10 text-amber-800 dark:text-amber-300 border-amber-500/30"
            : "px-2 py-0.5 text-[10px] bg-amber-500/10 text-amber-800 dark:text-amber-300 border-amber-500/30"
        }`}
        title="Synthetic event generated by RevivePay"
      >
        <FlaskConical className={`${size === "lg" ? "w-3.5 h-3.5" : "w-3 h-3"} text-amber-600 dark:text-amber-400`} />
        <span>Simulation</span>
      </span>
      {showSubtitle && (
        <span className="text-[10px] text-[var(--color-text-secondary)] font-sans">
          Synthetic event generated by RevivePay
        </span>
      )}
    </div>
  );
};
